# Generated by Django 4.2.9 on 2024-03-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exampleapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Child1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("one", models.CharField(max_length=50)),
                ("two", models.CharField(max_length=60)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Child2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("one", models.CharField(max_length=50)),
                ("two", models.CharField(max_length=60)),
                ("three", models.CharField(max_length=70)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
